// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onRgbColorChange();
void onThresholdDryChange();
void onMoistureOnChange();
void onRelay1Change();
void onRelay2Change();
void onUpdateDisplayChange();

String message;
float humidity;
float temperature;
CloudColoredLight rgbColor;
int light;
int moistValue;
int threshold_dry;
bool moisture_on;
bool relay_1;
bool relay_2;
bool updateDisplay;

void initProperties(){

  ArduinoCloud.addProperty(message, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humidity, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(temperature, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(rgbColor, READWRITE, ON_CHANGE, onRgbColorChange);
  ArduinoCloud.addProperty(light, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(moistValue, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(threshold_dry, READWRITE, ON_CHANGE, onThresholdDryChange);
  ArduinoCloud.addProperty(moisture_on, READWRITE, ON_CHANGE, onMoistureOnChange);
  ArduinoCloud.addProperty(relay_1, READWRITE, ON_CHANGE, onRelay1Change);
  ArduinoCloud.addProperty(relay_2, READWRITE, ON_CHANGE, onRelay2Change);
  ArduinoCloud.addProperty(updateDisplay, READWRITE, ON_CHANGE, onUpdateDisplayChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
