// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onMessageOnChange();
void onOnChange();
void onResetCounterChange();
void onStudentsCheckerChange();

String message;
float gyro_y;
int confirmed;
int counter;
int number_of_students;
bool doorChange;
bool message_on;
bool on;
bool reset_counter;
bool students_checker;

void initProperties(){

  ArduinoCloud.addProperty(message, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(gyro_y, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(confirmed, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(counter, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(number_of_students, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(doorChange, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(message_on, READWRITE, ON_CHANGE, onMessageOnChange);
  ArduinoCloud.addProperty(on, READWRITE, ON_CHANGE, onOnChange);
  ArduinoCloud.addProperty(reset_counter, READWRITE, ON_CHANGE, onResetCounterChange);
  ArduinoCloud.addProperty(students_checker, READWRITE, ON_CHANGE, onStudentsCheckerChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
